-- DB_CALENDER

CREATE DATABASE DB_CALENDER;
USE DB_CALENDER;

-- TBL_MEMBER
CREATE TABLE TBL_MEMBER (
	M_NO INT AUTO_INCREMENT, 
    M_ID VARCHAR(20) NOT NULL UNIQUE, 
    M_PW VARCHAR(100) NOT NULL, 
    M_MAIL VARCHAR(50) NOT NULL, 
    M_PHONE VARCHAR(30) NOT NULL, 
    M_REG_DATE DATETIME DEFAULT NOW(), 
    M_MOD_DATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(M_NO)
);

SELECT * FROM TBL_MEMBER;

-- PRE_USER, USER

ALTER TABLE TBL_MEMBER ADD COLUMN M_ROLE VARCHAR(10) DEFAULT 'PRE_USER';

DESC TBL_MEMBER;
-- TBL_PLAN
CREATE TABLE TBL_PLAN (
	P_NO			INT AUTO_INCREMENT,							
    P_ORI_NO		INT,				-- 최초 일정 NO			
    P_ORI_OWNER_ID	VARCHAR(20),		-- 최초 일정 등록자 ID		gildong		gildong
    M_ID 			VARCHAR(20),		-- 일정 등록자 ID			gildong     chanho
    P_YEAR			INT,
    P_MONTH			INT,
    P_DATE			INT,
    P_TITLE			VARCHAR(100),
    P_BODY			VARCHAR(100),
    P_IMG_NAME		VARCHAR(50),
    P_REG_DATE		DATETIME DEFAULT NOW(),
    P_MOD_DATE		DATETIME DEFAULT NOW(),
    PRIMARY KEY(P_NO)
);

SELECT * FROM TBL_PLAN;
DELETE FROM TBL_PLAN;

-- 	TBL_COMMENT
CREATE TABLE TBL_COMMENT (
	C_NO		INT AUTO_INCREMENT,
    P_ORI_NO	INT,
    M_ID		VARCHAR(20),
    C_TXT		VARCHAR(100),
    C_REG_DATE	DATETIME DEFAULT NOW(),
    C_MOD_DATE	DATETIME DEFAULT NOW(),
    PRIMARY KEY(C_NO)
);

SELECT * FROM TBL_COMMENT;


